In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import torch

In [3]:
import torch.nn as nn

In [4]:
df=pd.read_csv('iris.csv')

In [5]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [7]:
from torch.utils.data import TensorDataset,DataLoader

In [8]:
data=df.drop(['target'],axis=1).values

In [9]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
labels=df['target'].values

In [13]:
labels=labels.reshape(-1,1)

In [14]:
labels

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [15]:
iris=TensorDataset(torch.FloatTensor(data),torch.LongTensor(labels))

In [16]:
iris

In [18]:
for i in iris:
    print(i)

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor([0]))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor([0]))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor([0]))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor([0]))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor([0]))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor([0]))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor([0]))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor([0]))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor([0]))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor([0]))
(tensor([5.4000, 3.7000, 1.5000, 0.2000]), tensor([0]))
(tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor([0]))
(tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor([0]))
(tensor([4.3000, 3.0000, 1.1000, 0.1000]), tensor([0]))
(tensor([5.8000, 4.0000, 1.2000, 0.2000]), tensor([0]))
(tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor([0]))
(tensor([5.4000, 3.9000, 1.3000, 0.4000]), tensor([0]))
(tensor([5.1000, 3.5000, 1.4000, 0.3000]), tenso

In [19]:
iris_loader=DataLoader(iris,batch_size=50,shuffle=True)

In [20]:
iris_loader

In [21]:
for i in iris_loader:
    print(i)

[tensor([[7.2000, 3.6000, 6.1000, 2.5000],
        [5.5000, 2.4000, 3.8000, 1.1000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [4.9000, 2.4000, 3.3000, 1.0000],
        [6.3000, 2.7000, 4.9000, 1.8000],
        [5.7000, 2.5000, 5.0000, 2.0000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [5.5000, 2.6000, 4.4000, 1.2000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [5.0000, 2.0000, 3.5000, 1.0000],
        [7.4000, 2.8000, 6.1000, 1.9000],
        [7.3000, 2.9000, 6.3000, 1.8000],
        [5.1000, 3.8000, 1.6000, 0.2000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [5.1000, 3.8000, 1.5000, 0.3000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [5.0000, 2.3000, 3.3000, 1.0000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [7.9000, 3.8000, 6.4000, 2.0000],
        [6.2000, 2.8000, 4.8000, 1.8000],
        [6.3000, 2.9000, 5.6000, 